spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: 391738
  flyway:
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: 391738
